# Generated by Django 4.1.1 on 2022-09-12 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("articlesapp", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="article",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        )
    ]
