# Generated by Django 4.1.1 on 2022-09-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("todoapp", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="todomodel", name="task", field=models.CharField(max_length=50)
        )
    ]
