# Generated by Django 4.1.1 on 2022-09-11 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoReq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("videotitle", models.CharField(max_length=20)),
                ("videodesc", models.TextField()),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        )
    ]
